# %RAML 1.0
title: Pet Pal API
baseUri: http://localhost:3000/api
version: 1.0

/users:
  get:
    responses: 
          200:
  put:
  post:
  delete:
  /{userId}:
    get:
      responses: 
              200:

    put:
      responses: 
              200: 
              
    post:
      responses: 
              200:
    delete:
      responses:
              200:
    /pet:
      get:
      put:
      post:
      delete:
    /{petId}:
      get:
      put:
      post:
      delete:
  

