# %RAML 1.0
title: Pet Pal API
baseUri: http://localhost:3000/api
version: 1.0

/users:
  /{userId}:
/pet:
  /{petId}:
    /breeds:
      /{breedId}:
    /meals:
      /{mealId}:
    /medications:
      /{medicationId}:
    /healthevents:
      /{healtheventsId}:
    /images:
      /{imageId}:
/species:
  /{speciesId}:
/breeds:
  /{breedId}:  
/foods:
  /{foodId}:
/medicines:
  /{medicineId}:

