openapi: '3.0.2'
info:
  title: PetPal API
  version: '0.1.0'
servers:
  - url: http://localhost:3000/

tags:
  - name: Pets
  - name: Users
  - name: Species
  - name: Breeds

paths:
  /breeds:
    get:
      description: ''
      parameters: []
      tags:
        - Breeds
      responses:
        '200':
          description: OK
  /pets:
    get:
      summary: Get all of the user's pets
      description: ''
      parameters: []
      tags:
        - Pets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              example:
                - id: 43
                  name: 'Brian Griffin'
                  speciesId: 1
                  age: 27
                - id: 44
                  name: 'Snowball II'
                  speciesId: 2
                  age: 11
    post:
      summary: Create a pet
      description: Create a pet belonging to the currently logged in user
      tags:
        - Pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PetForm'
            example:
              name: 'Brian Griffin'
              speciesId: 1
              age: 27
      responses:
        '201':
          description: Created
          headers:
            'Location':
              schema:
                type: string
              description: Relative path of the newly created pet object (ex. /api/pets/43/)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
              example:
                id: 43
                userId: 0
                speciesId: 1
                name: 'Brian Griffin'
                age: 27
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                example:
                  - message: 'Required: speciesId'
                  - message: 'Invalid value: age'
        '401':
          description: Unauthorized
  /pets/{petId}:
    get:
      summary: "Get one of the user's pets"
      description: ''
      parameters: []
      tags:
        - Pets
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
    put:
      summary: 'Update a pet'
      description: ''
      parameters: []
      tags:
        - Pets
      responses:
        '200':
          description: OK
    delete:
      summary: 'Delete a pet'
      description: ''
      parameters: []
      tags:
        - Pets
      responses:
        '200':
          description: OK
  /species:
    get:
      description: ''
      parameters: []
      tags:
        - Species
      responses:
        '200':
          description: OK
  /users:
    get:
      description: 'Get information about the currently logged in user'
      parameters: []
      tags:
        - Users
      responses:
        '200':
          description: OK
    post:
      description: ''
      parameters: []
      tags:
        - Users
      responses:
        '200':
          description: OK

components:
  schemas:
    Pet:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        userId:
          type: integer
        speciesId:
          type: integer
        age:
          type: integer
    PetForm:
      type: object
      properties:
        name:
          type: string
        speciesId:
          type: integer
        age:
          type: integer
  securitySchemes:
    name:
      type: http
      scheme: bearer
      bearerFormat: JWT
